//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevxControlsSamples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Occupation { get; set; }
        public string EducationLevel { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<System.DateTime> LastPurchaseDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Column21 { get; set; }
        public Nullable<int> Column22 { get; set; }
        public Nullable<decimal> Column23 { get; set; }
        public Nullable<System.DateTime> Column24 { get; set; }
        public string Column51 { get; set; }
        public Nullable<int> Column52 { get; set; }
        public Nullable<decimal> Column53 { get; set; }
        public Nullable<System.DateTime> Column54 { get; set; }
    }
}
